#
#Tue Mar 31 14:24:26 BST 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[--remote-allow-origins\=*, --disable-web-security, --window-size\=1920,1080, --no-sandbox, --disable-dev-shm-usage], extensions\=[]}
